#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 11, 2020 01:35:00 PM EAT  platform: Linux

import sys

import tkinter as tk
import tkinter.ttk as ttk

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

    global file_path, ser_port, sample_interval, no_samples, cycle_time

    file_path = kwargs.get('path')
    ser_port = kwargs.get('port')
    sample_interval = int(kwargs.get('s_interval'))/0.3
    no_samples = int(kwargs.get('samples'))
    cycle_time = int(kwargs.get('cycle_time'))

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import tk_plot
    tk_plot.vp_start_gui()




